// Sprint 3 — NightReview domain model.
// Represents end-of-day closure, accountability summary, and recovery planning.
// Pure Swift struct. No SwiftData, no Supabase, no persistence.
import Foundation

struct NightReview: Identifiable, Codable, Equatable, Hashable, Sendable {
    let id: UUID
    var date: Date
    var completedCriticalTaskIDs: [UUID]
    var missedCriticalTaskIDs: [UUID]
    var completedHabitIDs: [UUID]
    var missedHabitIDs: [UUID]
    var hydrationCompleted: Bool
    var exerciseCompleted: Bool
    var sleepRoutineStarted: Bool
    var failureReason: String?          // nil = no failure to report
    var excuseDetected: Bool            // flagged by local logic, not AI
    var recoveryPlan: String?           // generated by DailyRoutinePolicy
    var completedAt: Date?
    let createdAt: Date
    var updatedAt: Date

    init(
        id: UUID = UUID(),
        date: Date = Date(),
        completedCriticalTaskIDs: [UUID] = [],
        missedCriticalTaskIDs: [UUID] = [],
        completedHabitIDs: [UUID] = [],
        missedHabitIDs: [UUID] = [],
        hydrationCompleted: Bool = false,
        exerciseCompleted: Bool = false,
        sleepRoutineStarted: Bool = false,
        failureReason: String? = nil,
        excuseDetected: Bool = false,
        recoveryPlan: String? = nil,
        completedAt: Date? = nil,
        createdAt: Date = Date(),
        updatedAt: Date = Date()
    ) {
        self.id = id
        self.date = date
        self.completedCriticalTaskIDs = completedCriticalTaskIDs
        self.missedCriticalTaskIDs = missedCriticalTaskIDs
        self.completedHabitIDs = completedHabitIDs
        self.missedHabitIDs = missedHabitIDs
        self.hydrationCompleted = hydrationCompleted
        self.exerciseCompleted = exerciseCompleted
        self.sleepRoutineStarted = sleepRoutineStarted
        self.failureReason = failureReason
        self.excuseDetected = excuseDetected
        self.recoveryPlan = recoveryPlan
        self.completedAt = completedAt
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    var isComplete: Bool { completedAt != nil }

    var missedCriticalCount: Int { missedCriticalTaskIDs.count }
    var completedCriticalCount: Int { completedCriticalTaskIDs.count }
    var totalCriticalCount: Int { completedCriticalCount + missedCriticalCount }

    var executionSummary: String {
        let critical = completedCriticalCount
        let total = totalCriticalCount
        guard total > 0 else { return "No critical commitments today." }
        if critical == total { return "All \(total) critical commitments completed." }
        return "\(critical)/\(total) critical commitments completed."
    }

    // Detects excuse-like language patterns (local, no AI)
    static func detectExcuse(in reason: String?) -> Bool {
        guard let reason, !reason.isEmpty else { return false }
        let lower = reason.lowercased()
        let excuseMarkers = ["didn't have time", "too tired", "forgot", "was busy",
                             "too hard", "it's fine", "next time", "couldn't be bothered"]
        return excuseMarkers.contains { lower.contains($0) }
    }
}
