#!/usr/bin/env bash
# =============================================================================
# Oathen — Sprint 1 Validation Script
# Goal: verify the SwiftUI app shell meets all Sprint 1 acceptance criteria.
# Does NOT require Xcode installed to run; will skip build steps if unavailable.
# Generates: validation/sprint1_validation_report.md
#
# Build approach (when Xcode is available):
#   iOS    → -target Oathen_iOS  -sdk iphonesimulator  (no simulator runtime needed)
#   macOS  → -target Oathen_macOS -sdk macosx           (native)
#   watchOS→ -target OathenWatch  -sdk watchsimulator   (no simulator runtime needed)
# =============================================================================
set -euo pipefail

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
PASS=0
FAIL=0
WARN=0
LINES=()

log()  { LINES+=("$1"); echo "$1"; }
pass() { PASS=$((PASS+1)); log "  ✅  $1"; }
fail() { FAIL=$((FAIL+1)); log "  ❌  $1"; }
warn() { WARN=$((WARN+1)); log "  ⚠️   $1"; }
section() { log ""; log "## $1"; log ""; }

# ---------------------------------------------------------------------------
# Goal 0 — Confirm repo root
# ---------------------------------------------------------------------------
section "Goal 0 — Repository Root"

if [[ ! -f "project.yml" ]]; then
    echo "ERROR: Run this script from the repository root (where project.yml lives)."
    exit 1
fi

REPO_ROOT="$(pwd)"
REPORT_DIR="validation"
mkdir -p "$REPORT_DIR/logs"

pass "Repo root: $REPO_ROOT"
pass "project.yml found"

# ---------------------------------------------------------------------------
# Goal 1 — Required documentation files
# ---------------------------------------------------------------------------
section "Goal 1 — Documentation Files"

DOCS=(
    "README.md"
    "docs/PROJECT_CONTEXT.md"
    "docs/ARCHITECTURE.md"
    "docs/DATA_MODEL.md"
    "docs/UX_FLOWS.md"
    "docs/DESIGN_SYSTEM.md"
    "docs/SPRINT_PLAN.md"
    "docs/DECISION_LOG.md"
    "docs/SCOPE_CONTROL.md"
    "docs/SECURITY_PRIVACY.md"
    "docs/AI_SYSTEM.md"
    "docs/COST_MODEL.md"
)

for doc in "${DOCS[@]}"; do
    if [[ -f "$doc" ]]; then
        pass "$doc exists"
    else
        fail "$doc MISSING"
    fi
done

# Apple API language audit (must say "API-supported", not bare "Confirmed")
if grep -r --include="*.md" "^| Confirmed" docs/ >/dev/null 2>&1; then
    fail "Found legacy 'Confirmed' in API capability table — must use 'API-supported (user permission required)'"
else
    pass "No legacy 'Confirmed' API language detected"
fi

# ---------------------------------------------------------------------------
# Goal 2 — Detect Oathen.xcodeproj
# ---------------------------------------------------------------------------
section "Goal 2 — Xcode Project"

if [[ -d "Oathen.xcodeproj" ]]; then
    pass "Oathen.xcodeproj exists"
else
    fail "Oathen.xcodeproj NOT FOUND — run: xcodegen generate"
fi

if [[ -f "project.yml" ]]; then
    pass "project.yml (XcodeGen spec) present"
fi

# ---------------------------------------------------------------------------
# Goal 3 — Detect xcodebuild availability
# ---------------------------------------------------------------------------
section "Goal 3 — xcodebuild Availability"

XCODE_AVAILABLE=false
if xcodebuild -version >/dev/null 2>&1; then
    XCODE_AVAILABLE=true
    XCODE_VER="$(xcodebuild -version 2>&1 | head -1)"
    pass "xcodebuild available: $XCODE_VER"
else
    warn "xcodebuild unavailable — Xcode app is not installed on this machine."
    warn "Install Xcode from the Mac App Store, then re-run this script."
    warn "Build goals (4, 5, 6, 7) will be SKIPPED."
fi

# ---------------------------------------------------------------------------
# Goal 4 — xcodebuild -list: verify exact scheme names
# ---------------------------------------------------------------------------
section "Goal 4 — Project Schemes"

if [[ "$XCODE_AVAILABLE" == "true" ]]; then
    SCHEME_LIST="$(xcodebuild -list -project Oathen.xcodeproj 2>&1)"
    log "$SCHEME_LIST"

    # Check for exact scheme names generated by XcodeGen multiplatform target
    if echo "$SCHEME_LIST" | grep -q "Oathen_iOS"; then
        pass "Scheme 'Oathen_iOS' detected"
    else
        fail "Scheme 'Oathen_iOS' not found — expected from XcodeGen multiplatform target"
    fi

    if echo "$SCHEME_LIST" | grep -q "Oathen_macOS"; then
        pass "Scheme 'Oathen_macOS' detected"
    else
        fail "Scheme 'Oathen_macOS' not found — expected from XcodeGen multiplatform target"
    fi

    if echo "$SCHEME_LIST" | grep -q "OathenWatch"; then
        pass "Scheme 'OathenWatch' detected"
    else
        fail "Scheme 'OathenWatch' not found — expected from watchOS target"
    fi
else
    warn "SKIPPED — xcodebuild not available"
fi

# ---------------------------------------------------------------------------
# Goal 5 — iOS build
# Uses -target Oathen_iOS -sdk iphonesimulator (no simulator runtime required)
# ---------------------------------------------------------------------------
section "Goal 5 — iOS Build"

if [[ "$XCODE_AVAILABLE" == "true" ]]; then
    LOG_IOS="$REPORT_DIR/logs/ios_build.log"
    log "  Running: xcodebuild build -target Oathen_iOS -sdk iphonesimulator ..."
    if xcodebuild build \
        -target Oathen_iOS \
        -sdk iphonesimulator \
        CODE_SIGNING_ALLOWED=NO \
        -quiet >"$LOG_IOS" 2>&1; then
        pass "iOS build SUCCEEDED"
    else
        fail "iOS build FAILED — log: $LOG_IOS"
        grep "error:" "$LOG_IOS" | head -10 | while IFS= read -r line; do log "    $line"; done
    fi
else
    warn "SKIPPED — xcodebuild not available"
fi

# ---------------------------------------------------------------------------
# Goal 6 — macOS build
# Uses -target Oathen_macOS -sdk macosx
# ---------------------------------------------------------------------------
section "Goal 6 — macOS Build"

if [[ "$XCODE_AVAILABLE" == "true" ]]; then
    LOG_MACOS="$REPORT_DIR/logs/macos_build.log"
    log "  Running: xcodebuild build -target Oathen_macOS -sdk macosx ..."
    if xcodebuild build \
        -target Oathen_macOS \
        -sdk macosx \
        CODE_SIGNING_ALLOWED=NO \
        -quiet >"$LOG_MACOS" 2>&1; then
        pass "macOS build SUCCEEDED"
    else
        fail "macOS build FAILED — log: $LOG_MACOS"
        grep "error:" "$LOG_MACOS" | head -10 | while IFS= read -r line; do log "    $line"; done
    fi
else
    warn "SKIPPED — xcodebuild not available"
fi

# ---------------------------------------------------------------------------
# Goal 7 — watchOS build
# Uses -target OathenWatch -sdk watchsimulator (no simulator runtime required)
# ---------------------------------------------------------------------------
section "Goal 7 — watchOS Build"

if [[ "$XCODE_AVAILABLE" == "true" ]]; then
    LOG_WATCH="$REPORT_DIR/logs/watchos_build.log"
    log "  Running: xcodebuild build -target OathenWatch -sdk watchsimulator ..."
    if xcodebuild build \
        -target OathenWatch \
        -sdk watchsimulator \
        CODE_SIGNING_ALLOWED=NO \
        -quiet >"$LOG_WATCH" 2>&1; then
        pass "watchOS build SUCCEEDED"
    else
        fail "watchOS build FAILED — log: $LOG_WATCH"
        grep "error:" "$LOG_WATCH" | head -10 | while IFS= read -r line; do log "    $line"; done
    fi
else
    warn "SKIPPED — xcodebuild not available"
fi

# ---------------------------------------------------------------------------
# Goal 8 — Forbidden implementation scan (Swift source files only)
# ---------------------------------------------------------------------------
section "Goal 8 — Forbidden Implementation Scan"

SWIFT_FILES=$(find . \
    -name "*.swift" \
    -not -path "./.build/*" \
    -not -path "./Oathen.xcodeproj/*" \
    -not -path "*/.swiftpm/*" \
    -not -path "./build/*" \
    | sort)

SWIFT_COUNT=$(echo "$SWIFT_FILES" | grep -c ".swift" || true)
log "  Scanning $SWIFT_COUNT Swift source files..."

check_forbidden() {
    local pattern="$1"
    local label="$2"
    local context="$3"

    if echo "$SWIFT_FILES" | xargs grep -l "$pattern" 2>/dev/null | head -1 | grep -q "."; then
        local found_in
        found_in=$(echo "$SWIFT_FILES" | xargs grep -l "$pattern" 2>/dev/null | tr '\n' ' ')
        fail "FORBIDDEN: $label ($pattern) found in: $found_in"
        log "    Context: $context"
    else
        pass "No $label ($pattern) found"
    fi
}

# Supabase
check_forbidden "import Supabase"             "Supabase SDK import"        "Backend — Sprint 5+"
check_forbidden "SupabaseClient"              "SupabaseClient usage"       "Backend — Sprint 5+"
check_forbidden "supabase\.from("            "Supabase query"             "Backend — Sprint 5+"

# HealthKit
check_forbidden "import HealthKit"            "HealthKit import"           "HealthKit — Sprint 4"
check_forbidden "HKHealthStore"               "HKHealthStore"              "HealthKit — Sprint 4"
check_forbidden "requestAuthorization"        "HealthKit auth request"     "HealthKit — Sprint 4"

# AI / LLM provider calls
check_forbidden "openai\.com"                 "OpenAI endpoint hardcoded"  "AI — Sprint 7"
check_forbidden "api\.anthropic\.com"         "Anthropic endpoint hardcoded" "AI — Sprint 7"
check_forbidden "generativelanguage\.google"  "Gemini endpoint hardcoded"  "AI — Sprint 7"
check_forbidden "ChatCompletion"              "OpenAI ChatCompletion call"  "AI — Sprint 7"
check_forbidden "AnthropicClient"             "Anthropic SDK client"       "AI — Sprint 7"

# Persistence
check_forbidden "@Model"                      "SwiftData @Model"           "Persistence — Sprint 2+"
check_forbidden "ModelContainer"              "SwiftData ModelContainer"   "Persistence — Sprint 2+"
check_forbidden "NSManagedObject"             "Core Data NSManagedObject"  "Persistence — Sprint 2+"
check_forbidden "NSPersistentContainer"       "Core Data stack"            "Persistence — Sprint 2+"

# Auth
check_forbidden "ASAuthorizationController"   "Sign in with Apple"         "Auth — Sprint 5"
check_forbidden "GIDSignIn"                   "Google Sign-In"             "Auth — Sprint 5"

# Notifications
check_forbidden "UNUserNotificationCenter"    "Notification scheduling"    "Notifications — Sprint 6"
check_forbidden "requestAuthorization.*notif" "Notification permission"    "Notifications — Sprint 6"

# WidgetKit
check_forbidden "import WidgetKit"            "WidgetKit import"           "Widgets — Sprint 9+"
check_forbidden "TimelineProvider"            "WidgetKit TimelineProvider" "Widgets — Sprint 9+"

# ActivityKit / Live Activities
check_forbidden "import ActivityKit"          "ActivityKit import"         "Live Activities — Sprint 9+"
check_forbidden "ActivityAttributes"          "Live Activity attributes"   "Live Activities — Sprint 9+"

# WatchConnectivity
check_forbidden "import WatchConnectivity"    "WatchConnectivity"          "Watch sync — Sprint 6"
check_forbidden "WCSession"                   "WCSession"                  "Watch sync — Sprint 6"

# DeviceActivity / Screen Time / FamilyControls
check_forbidden "import DeviceActivity"       "DeviceActivity"             "Feasibility-gated — Sprint 11"
check_forbidden "import FamilyControls"       "FamilyControls"             "Feasibility-gated — Sprint 11"
check_forbidden "import ManagedSettings"      "ManagedSettings"            "Feasibility-gated — Sprint 11"
check_forbidden "DeviceActivityMonitor"       "DeviceActivityMonitor"      "Feasibility-gated — Sprint 11"

# Core Data model files
if find . -name "*.xcdatamodeld" -not -path "./.build/*" -not -path "./build/*" | grep -q "."; then
    fail "FORBIDDEN: .xcdatamodeld file found — use SwiftData in Sprint 2+"
else
    pass "No .xcdatamodeld Core Data model files"
fi

# ---------------------------------------------------------------------------
# Goal 9 — Required Swift source files exist
# ---------------------------------------------------------------------------
section "Goal 9 — Required Source Files"

REQUIRED_SOURCES=(
    "Oathen/App/OathenApp.swift"
    "Oathen/App/Root/PlatformRouter.swift"
    "Oathen/App/Root/OathenTab.swift"
    "Oathen/App/Root/OathenRootView.swift"
    "Oathen/Core/DesignSystem/OathenColors.swift"
    "Oathen/Core/DesignSystem/OathenTypography.swift"
    "Oathen/Core/DesignSystem/OathenSpacing.swift"
    "Oathen/Core/DesignSystem/OathenRadius.swift"
    "Oathen/Core/DesignSystem/OathenComponents.swift"
    "Oathen/Core/Foundation/AppEnvironment.swift"
    "Oathen/Core/Foundation/PlaceholderData.swift"
    "Oathen/Features/Today/TodayView.swift"
    "Oathen/Features/Goals/GoalsView.swift"
    "Oathen/Features/Coach/CoachView.swift"
    "Oathen/Features/Health/HealthView.swift"
    "Oathen/Features/You/YouView.swift"
    "Oathen/Features/MacDashboard/MacDashboardView.swift"
    "OathenWatch/OathenWatchApp.swift"
    "OathenWatch/WatchHomeView.swift"
)

for src in "${REQUIRED_SOURCES[@]}"; do
    if [[ -f "$src" ]]; then
        pass "$src"
    else
        fail "$src MISSING"
    fi
done

# ---------------------------------------------------------------------------
# Goal 10 — Summary
# ---------------------------------------------------------------------------
section "Validation Summary"

TOTAL=$((PASS + FAIL + WARN))
log "  Total checks : $TOTAL"
log "  Passed       : $PASS"
log "  Failed       : $FAIL"
log "  Warnings     : $WARN"
log ""

if [[ $FAIL -eq 0 ]]; then
    log "  ✅  ALL CHECKS PASSED — Sprint 1 shell is valid."
    STATUS="PASSED"
else
    log "  ❌  $FAIL CHECKS FAILED — address the failures above before Sprint 2."
    STATUS="FAILED ($FAIL failures)"
fi

if [[ $WARN -gt 0 ]]; then
    log "  ⚠️   $WARN warnings (usually: Xcode not installed — install before final validation)"
fi

# ---------------------------------------------------------------------------
# Write report
# ---------------------------------------------------------------------------
REPORT="$REPORT_DIR/sprint1_validation_report.md"

{
    echo "# Sprint 1 Validation Report"
    echo ""
    echo "**Status:** $STATUS"
    echo "**Date:** $(date '+%Y-%m-%d %H:%M:%S %Z')"
    echo "**Repo:** $REPO_ROOT"
    echo ""
    echo "---"
    echo ""
    for line in "${LINES[@]}"; do
        echo "$line"
    done
    echo ""
    echo "---"
    echo ""
    echo "## Build Approach"
    echo ""
    echo "Builds use \`-target\` + \`-sdk\` (no simulator runtime required):"
    echo "- iOS:    \`-target Oathen_iOS -sdk iphonesimulator\`"
    echo "- macOS:  \`-target Oathen_macOS -sdk macosx\`"
    echo "- watchOS:\`-target OathenWatch -sdk watchsimulator\`"
    echo ""
    echo "Full build logs: \`$REPORT_DIR/logs/\`"
    echo ""
    echo "## Next Steps"
    echo ""
    if [[ "$XCODE_AVAILABLE" == "false" ]]; then
        echo "1. Install Xcode from the Mac App Store."
        echo "2. Run \`sudo xcode-select -s /Applications/Xcode.app/Contents/Developer\`"
        echo "3. Re-run this script to validate iOS, macOS, and watchOS builds."
    fi
    if [[ $FAIL -eq 0 ]]; then
        echo "- Sprint 1 shell is validated. Proceed to Sprint 2 planning."
    else
        echo "- Address the $FAIL failing checks above, then re-run this script."
    fi
} > "$REPORT"

log ""
log "  Report written to: $REPORT"
log ""
